2.5.x ES and Graphite HTTP dashboards.
typesafehub/cinnamon-ui pull request #18
Opened 2017-07-27 14:26 UTC by henrikengstrom

2017-07-27 23:52 UTC, pvlugter requested changes
I haven't tried these out yet, but noticed some things when skimming through the json.

Also, have we checked that we have 10s intervals set. We've had those issues with sawtooth graphs when we haven't had that.

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/elasticsearch/http-client-metrics.json
> +  "dashboard": {
Dashboards in this repo shouldn't have the "dashboard" wrapper so that they can be loaded from the Grafana load json UI. Was loading this tested?

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/graphite/http-client-metrics.json
> +      "query": "*.gauges.servers.*.apps.*.metrics.akka-http.systems.*.client-pools.*",
Shouldn't we have server and app variables as well?

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/graphite/http-client-metrics.json
> +            "target": "aliasByNode(*.gauges.servers.*.apps.*.metrics.akka-http.systems.*.client-pools.*.connections, 11)",
Should there be an actor system variable as well?

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/graphite/http-client-metrics.json
> +        "title": "$Services - Requests: 1min rate",
Is this title correct? The targets show service response time.

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/graphite/http-server-metrics.json
> +              "target": "aliasByNode(stats.gauges.servers.*.apps.*.metrics.akka-http.systems.*.http-servers.$HttpServers.connections.min15_rate, 11, 12, 13)",
Should we still have min1, min5, and min15 rates in the same graph?

2017-07-27 23:52 UTC, pvlugter commented on cinnamon/2.5.x/grafana/4.x/graphite/http-server-metrics.json
> +              "target": "aliasByNode(stats.gauges.servers.*.apps.*.metrics.akka-http.systems.*.http-servers.$HttpServers.responses-2xx.min15_rate, 11, 13)",
Also here: graph has min1, min5, and min15 rates?

2017-07-28 14:16 UTC, henrikengstrom commented on cinnamon/2.5.x/grafana/4.x/graphite/http-client-metrics.json
> +      "query": "*.gauges.servers.*.apps.*.metrics.akka-http.systems.*.client-pools.*",
I can add that.

2017-07-28 14:16 UTC, henrikengstrom commented on cinnamon/2.5.x/grafana/4.x/graphite/http-client-metrics.json
> +            "target": "aliasByNode(*.gauges.servers.*.apps.*.metrics.akka-http.systems.*.client-pools.*.connections, 11)",
Sure. Will add.

2017-07-28 14:17 UTC, henrikengstrom commented on cinnamon/2.5.x/grafana/4.x/graphite/http-server-metrics.json
> +              "target": "aliasByNode(stats.gauges.servers.*.apps.*.metrics.akka-http.systems.*.http-servers.$HttpServers.connections.min15_rate, 11, 12, 13)",
I will remove.

2017-07-30 22:35 UTC, pvlugter commented
Added some small tweaks and fixes to the dashboards.

2017-07-30 22:35 UTC, pvlugter approved these changes

2017-07-30 22:36 UTC, merged